### ISSUE TITLE
Implement database 

### ISSUE THREAD

**Issue by Grimcheese** [Grimcheese/GardenStation#1]
GardenStation needs a database to be implemented to store all recorded data in an easily accessible way. The project relies on recording and storing data so the database is a major feature that needs to be implemented. 

## Main Specs
- Accessible using Python programming language
- Can be run from a Raspberry Pi
- Takes up minimal storage space
- Must be able to backup to secondary device

## Tasks
- [x] Research database solution
- [x] Download/Install software
- [x] Develop database API to interact with Flask web app

* removed integrating the database with the web app task as that can be it's own issue

**Comment by Grimcheese** [comment]
Using SQLite for the DBMS as it is lightweight and will be suitable to run on a RPI.

**Comment by Grimcheese** [comment]
First working version of Database API is complete with testing 84d13e898 

It contains method calls to insert records into a moisture_readings table, retrieve all records stored from a device and retrieve records between a range of dates.

**Comment by Grimcheese** [comment]
Closed with pull request #6
